resources:
  - ../../../../composite/infra
  - ../../../../function/clusterctl
  - ../../../../function/airshipctl-catalogues
  - ../../../../function/baremetal-operator
  - ../../../../function/hwcc
  - ../../../../function/helm-operator

patchesStrategicMerge:
  - patch_bmo_config.yaml

commonLabels:
  airshipit.org/stage: initinfra

transformers:
  - ../../../../composite/infra/replacements
  - ../../../../function/baremetal-operator/replacements
  - ../../../../function/helm-operator/replacements
